# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfallapp', '0003_auto_20180507_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_rainfall',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
